input AddItemInput {
  name: String!
  description: String
  quantity: Int
  completed: Boolean
}

type Item {
  id: Int!
  name: String!
  description: String
  quantity: Int
  completed: Boolean
}

type AddItemPayload {
  id: Int!
}

type Query {
  items: [Item]
}

type Mutation {
  addItem(item: AddItemInput!): AddItemPayload!
}
