input AddItemInput {
  name: String!
  description: String
  quantity: Int
  completed: Boolean
}

input UpdateItemInput {
  id: Int!
  name: String
  description: String
  quantity: String
  completed: String
}

input DeleteItemInput {
  id: Int!
}

type Item {
  id: Int!
  name: String!
  description: String
  quantity: Int
  completed: Boolean
}

type AddItemPayload {
  item: Item!
}

type UpdateItemPayload {
  item: Item!
}

type Query {
  items: [Item]
}

type Mutation {
  addItem(item: AddItemInput!): AddItemPayload!
  updateItem(item: UpdateItemInput!): UpdateItemPayload!
  deleteItem(item: DeleteItemInput!): UpdateItemPayload!
}
